version: '3.9'

services:
  frontend-prod-builder:
    restart: "on-failure"
    build:
      dockerfile: .docker-compose/frontend-prod-builder/Dockerfile
      context: ./
    volumes:
      - ./frontend:/code/
    environment:
      REACT_APP_API_DASHBOARD_MAIN_BASE_ADDR: http://localhost:8082/api/dashboard-main

  frontend-prod:
    restart: 'always'
    image: nginx:1.21.6-alpine
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "3001:80"
    depends_on:
      - api-dashboard-main
      - frontend-prod-builder

  api-system:
    restart: 'always'
    build:
      dockerfile: .docker-compose/golang-runner/Dockerfile
      context: ./
    volumes:
      - ./:/go/src/github.com/goforbroke1006/onix
    working_dir: /go/src/github.com/goforbroke1006/onix
    command: "api system"
    ports: [ "8081:8080" ]
    environment: { DB_HOST: postgres }
    depends_on: [ postgres ]

  api-dashboard-main:
    restart: 'always'
    build:
      dockerfile: .docker-compose/golang-runner/Dockerfile
      context: ./
    volumes:
      - ./:/go/src/github.com/goforbroke1006/onix
    working_dir: /go/src/github.com/goforbroke1006/onix
    command: "api dashboard-main"
    ports: [ "8082:8080" ]
    environment: { DB_HOST: postgres }
    depends_on: [ postgres ]

  daemon-metrics-extractor:
    restart: 'on-failure'
    build:
      dockerfile: .docker-compose/golang-runner/Dockerfile
      context: ./
    volumes:
      - ./:/go/src/github.com/goforbroke1006/onix
    working_dir: /go/src/github.com/goforbroke1006/onix
    command: "daemon metrics-extractor"
    environment: { DB_HOST: postgres }
    depends_on:
      - postgres
      - stub-prometheus

  stub-prometheus:
    restart: 'always'
    build:
      dockerfile: .docker-compose/golang-runner/Dockerfile
      context: ./
    volumes:
      - ./:/go/src/github.com/goforbroke1006/onix
    working_dir: /go/src/github.com/goforbroke1006/onix
    command: "stub prometheus"
    ports: [ "19090:19090" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:19090/api/v1/healthz" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    restart: 'on-failure'
    image: postgres:10.0
    environment:
      POSTGRES_DB: 'onix'
      POSTGRES_USER: 'onix'
      POSTGRES_PASSWORD: 'onix'
    ports: [ "5432:5432" ]
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    restart: 'on-failure'
    image: amacneil/dbmate:v1.12
    command: '-d /migrations up'
    environment:
      DATABASE_URL: postgres://onix:onix@postgres:5432/onix?sslmode=disable
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

  fixture:
    restart: 'on-failure'
    image: amacneil/dbmate:v1.12
    command: '-d /fixtures up'
    environment:
      DATABASE_URL: postgres://onix:onix@postgres:5432/onix?sslmode=disable
    volumes:
      - ./demo/fixtures:/fixtures
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgresql-data: ~