openapi: 3.0.3
info:
  title: System API
  description: System API
  version: 1.0.0
servers:
  - url: 'http//127.0.0.1:8081/api/system'
paths:
  /healthz:
    get:
      responses:
        200:
          description: health check for docker-compose
          content:
            application/json:
              schema:
                type: string
  /register/source:
    get:
      parameters:
        - in: query
          name: title
          required: true
          schema:
            type: string
        - in: query
          name: kind
          required: true
          schema:
            type: string
        - in: query
          name: address
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterSourceResponse'
  /register/criteria:
    get:
      parameters:
        - in: query
          name: service
          required: true
          schema:
            type: string
        - in: query
          name: title
          required: true
          schema:
            type: string
        - in: query
          name: selector
          required: true
          schema:
            type: string
        - in: query
          name: expected_dir
          required: true
          schema:
            type: string
        - in: query
          name: grouping_interval
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterCriteriaResponse'
  /register/release:
    get:
      parameters:
        - in: query
          name: service_name
          required: true
          schema:
            type: string
        - in: query
          name: release_name
          required: true
          schema:
            type: string
        - in: query
          name: start_at
          required: false
          schema:
            type: integer
            format: "int64"
      responses:
        200:
          description: successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterReleaseResponse'


components:
  schemas:
    RegisterSourceResponse:
      type: object
      required: [ status ]
      properties:
        status:
          type: string
          enum:
            - ok
            - fail
    RegisterCriteriaResponse:
      type: object
      required: [ status ]
      properties:
        status:
          type: string
          enum:
            - ok
            - fail
    RegisterReleaseResponse:
      type: object
      required: [ status ]
      properties:
        status:
          type: string
          enum:
            - ok
            - fail
