openapi: 3.0.3
info:
  title: System API
  description: System API
  version: 1.0.0
servers:
  - url: 'http//127.0.0.1:8081/api/system'
paths:
  /register:
    get:
      parameters:
        - in: query
          name: service_name
          required: true
          schema:
            type: string
        - in: query
          name: release_name
          required: true
          schema:
            type: string
        - in: query
          name: start_at
          required: false
          schema:
            type: integer
            format: "int64"
      responses:
        200:
          description: successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'


components:
  schemas:
    RegisterResponse:
      type: object
      required: [ status ]
      properties:
        status:
          type: string
          enum:
            - ok
            - fail
