name: CI (branch)
on:
  push:
    branches:
      - master
      - staging
      - develop
  pull_request:
    branches:
      - master
      - staging
      - develop
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Install dependencies
        run: |
          go version
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.2
          go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.9.1
          go install github.com/golang/mock/mockgen@v1.6.0
          go mod download
      - name: Print env
        run: |
          echo ${GOPATH}
      - name: Cache GOPATH
        id: cache-gopath
        uses: actions/cache@v3
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-gopath
      - name: Run build
        run: |
          go generate ./...
          go build .
      - name: Run vet & lint
        run: |
          go vet .
          golangci-lint run
      - name: Run testing
        run: go test -v ./...
      - name: Calc coverage
        run: go test -race -coverprofile=coverage.out ./...
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.out -service=github

  images:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push onix-backend
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: .build/backend/Dockerfile
          push: true
          tags: docker.io/goforbroke1006/onix-backend:latest

      - name: Build and push onix-dashboard-admin
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/dashboard-admin
          file: .build/frontend/Dockerfile
          push: true
          tags: docker.io/goforbroke1006/onix-dashboard-admin:latest

      - name: Build and push onix-dashboard-main
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/dashboard-main
          file: .build/frontend/Dockerfile
          push: true
          tags: docker.io/goforbroke1006/onix-dashboard-main:latest
