name: CIDD
on:
  push:
    branches:
      - master
      - staging
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Install dependencies
        run: |
          go version
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.2
          go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.9.1
          go install github.com/golang/mock/mockgen@v1.6.0
      - name: Run build
        run: |
          go generate ./...
          go build .
      - name: Run vet & lint
        run: |
          go vet .
          golangci-lint run
      - name: Run testing
        run: go test -v
#      - name: Send slack notification
#        uses: 8398a7/action-slack@v3
#        with:
#          status: ${{ job.status }}
#          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#        if: always()
