name: CI (tag)
on:
  create:
    tags:
      - v*
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.5'
      - name: Prepare
        run: |
          go version
          go mod download
          go generate ./...
          go build .
      - name: Run testing
        run: go test -v ./...
      - name: Calc coverage
        run: go test -race -coverprofile=coverage.out ./...
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.out -service=github

  images:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Print tag
        run: echo "Build tag ${{ env.GITHUB_REF_SLUG }}"

      - name: Build and push onix-backend
        uses: docker/build-push-action@v2
        with:
          pull: true
          context: ./
          file: .docker/backend/Dockerfile
          push: true
          tags: docker.io/goforbroke1006/onix-backend:${{ env.GITHUB_REF_SLUG }}

      - name: Build and push onix-frontend
        uses: docker/build-push-action@v2
        with:
          pull: true
          context: ./
          file: .docker/frontend/Dockerfile
          push: true
          tags: docker.io/goforbroke1006/onix-frontend:${{ env.GITHUB_REF_SLUG }}
