name: CI (tag)
on:
  create:
    tags:
      - v*
jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print tag
        run: echo "Build tag ${GITHUB_REF##*/}"

      - name: Build and push onix-backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .build/backend/Dockerfile
          push: true
          tags: "docker.io/goforbroke1006/onix-backend:${GITHUB_REF##*/}"

      - name: Build and push onix-dashboard-admin
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .build/frontend/Dockerfile
          push: true
          tags: "docker.io/goforbroke1006/onix-dashboard-admin:${GITHUB_REF##*/}"

      - name: Build and push onix-backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .build/frontend/Dockerfile
          push: true
          tags: "docker.io/goforbroke1006/onix-dashboard-main:${GITHUB_REF##*/}"
